### PR TITLE
Customized directories

### PR DESCRIPTION
**Pull request by naitian**
Instead of using hardcoded directories, it now lists all subdirectories of the home directory as options.
This would resolve issues #4 and #2.

Note: only tested on OSX 10.11; not sure how it works on windows.

### CODE REVIEW

**Comment by KamronSoldozy** [comment]
NAITIAN YOU CAN STOP WORKING ON THIS NOW LOL

**Comment by naitian** [comment]
Dude, I have to keep up my github contribution streak.

**Comment by KamronSoldozy** [comment]
oh ok continue

**Comment by naitian** [comment]
Can you merge this so I can close the issues?

**Pull request merged**
